### ISSUE TITLE
[AVM Module Issue]:  Dynamic "slow_request_with_path" is not expected here, azurerm_windows_webapp

### ISSUE THREAD

**Issue by thenewnano** [Azure/terraform-azurerm-avm-res-web-site#77]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.5.0 to 0.6.2

### Description

I wanted to upgrade from 0.4.0 to 0.6.x and now using  windows web apps, just Linux webapp for container, can't seem to find a way around this, I have health check disabled at the moment, nothing declared from my side regarding that. 
tried 0.5.0 as well same issue.

**Comment by donovm4** [comment]
hello @thenewnano - will look into this. Would you be able to share a code/error snippet, so that I may try to replicate this issue.

**Comment by thenewnano** [comment]
I could do that, probably as it fails on validate, the code I have has a couple of layers into it, but I have to create something for you, will do my best

**Comment by donovm4** [comment]
addressed in v0.6.3 release

**Comment by thenewnano** [comment]
@donovm4  thanks for the fix, I was about to create a sample project, auto heal enabled at the moment is commented out in my settings, don't recall how was it at the moment of the issue. will try the new version asap

**Comment by stredovek** [comment]
In my case it does not work in version 0.6.3.  I still receive following during terraform plan :
Error: Unsupported block type
in resource "azurerm_windows_web_app" "this":
│  102:           dynamic "slow_request_with_path" {
│
│ Blocks of type "slow_request_with_path" are not expected here.
********************************************************************************************
in resource "azurerm_linux_web_app" "this":
│  622:           dynamic "slow_request_with_path" {
│
│ Blocks of type "slow_request_with_path" are not expected here.
FYI I do not define any settings  for these variables and it worked before with version 0.6.0 when I last tested it.

**Comment by donovm4** [comment]
Hi @stredovek - I can work to implement an example that will show a passing configuration if that will help.

**Comment by stredovek** [comment]
@donovm4 . That will be best. Thank you in advance.

**Comment by thenewnano** [comment]
Just to add to this , it does not work for me either, but as I have not created a failing main file I didn't want to fight it

**Comment by donovm4** [comment]
@stredovek / @thenewnano : Would you be able to submit a sample of code with the module call? That will help me in trying to recreate this error. I will be working on a couple other issues and then submit a `v0.7.0` soon with an example.

**Comment by donovm4** [comment]
Please reference `v0.7.0` for the latest updates and the `example` of a configuration utilizing `auto_heal_enabled`
